jobs:
  - job: deploy
    displayName: Deploy
    # Increase default of 60 minutes https://go.microsoft.com/fwlink/?linkid=2077134
    timeoutInMinutes: 300
    steps:
      - script: mvn compile exec:java
        env:
          API_AUTH_CLIENT_ID: $(api-auth-client-id)
          API_AUTH_CLIENT_SECRET: $(api-auth-client-secret)
          API_RDP_CLIENT_ID: $(api-rdp-client-id)
          API_RDP_TENANT_ID: $(api-rdp-tenant-id)
          API_RDP_USER_ID: $(api-rdp-user-id)
