trigger:
  branches:
    include:
      - main  # Replace with your target branch name

stages:
  - stage: Publish_Zip_File
    displayName: 'Publish Zip File'
    jobs:
      - job: Publish_Zip_File_Job
        displayName: 'Publish Zip File'
        steps:
          - checkout: self

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '10-json/110-uiconfig/1106-entitytype/rock-entity-header_product_thing_uiConfig.json'  # Replace with the path to your folder in the repository
              includeRootFolder: true
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/files.zip'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Pipeline.Workspace)'
              artifactName: 'files.zip'  # Replace with your desired artifact name
              publishLocation: 'pipeline'
          
        

  
  - stage: Generate_Auth_Token
    displayName: 'Generate Auth Token'
    jobs:
      - job: Generate_Auth_Token_Job
        displayName: 'Generate Auth Token'
        steps:
          - checkout: self

          - script: |
              # Generate the authToken
              currentTime=$(date -u +"%Y-%m-%dT%H:%M:%S")
              request="POST https://etronds.riversand.com/api/binarystreamobjectservice/prepareUpload"
              clientId="rdpclient"  # Replace with your clientId
              userId="etronds.systemadmin@riversand.com"  # Replace with your userId
              clientAuthKey="J7UaRWQgxorI8mdfuu8y0mOLqzlIJo2hM3O4VfhX1PIeoa7CYVX_l0-BnHRtuSWB"  # Replace with your clientAuthKey
              signature=$(echo -n "$request&timeStamp=$currentTime" | openssl dgst -binary -sha256 -hmac "$clientAuthKey" | openssl base64 -e)
              authToken="$clientId,$userId,$signature"
    
              echo "##vso[task.setvariable variable=authToken]$authToken"
            displayName: 'Generate Auth Token'

  - stage: Get_Upload_URL
    displayName: 'Get Upload URL'
    jobs:
      - job: Get_Upload_URL_Job
        displayName: 'Get Upload URL'
        steps:
          - checkout: self

          - script: |
              # Retrieve the authToken from the previous stage
              authToken=$(echo "$authToken")

              # Make the API request to prepare the upload and extract the upload URL
              prepareUploadResponse=$(curl -X POST \
                -H "Content-Type: application/json" \
                -H "Authorization: $authToken" \
                -d '{}' \
                'https://etronds.riversand.com/api/binarystreamobjectservice/prepareUpload')

              # Extract the upload URL from the response
              uploadURL=$(echo "$prepareUploadResponse" | jq -r '.response.binaryStreamObjects[0].properties.uploadURL')

              echo "##vso[task.setvariable variable=uploadURL]$uploadURL"
            displayName: 'Get Upload URL'

  - stage: Deploy_File
    displayName: 'Deploy File'
    jobs:
      - job: Deploy_File_Job
        displayName: 'Deploy File'
        steps:
          - checkout: self
          - script: |

              echo $(uploadURL)  # Verify the value of the uploadURL variable
              curl -v -X PUT "$(uploadURL)" \

                --header "x-ms-meta-x_rdp_userroles: systemadmin" \
                --header "x-ms-meta-x_rdp_tenantid: etronds" \
                --header "x-ms-meta-originalfilename: files.zip" \
                --header "x-ms-blob-content-disposition: attachment; filename=files.zip" \
                --header "x-ms-meta-type: disposition" \
                --header "x-ms-meta-x_rdp_clientid: rdpclient" \
                --header "x-ms-meta-x_rdp_userid: etronds.systemadmin@riversand.com" \
                --header "x-ms-meta-binarystreamobjectid: guid" \
                --header "x-ms-blob-type: BlockBlob" \
                --header "Content-Type: application/zip" \

                --data-binary "@$(Pipeline.Workspace)/files.zip"
        
              echo "Folder deployed successfully."
            displayName: 'Deploy Folder'

  - stage: Get_Details_From_Tenant
    displayName: 'Get Details From Tenant'
    jobs:
      - job: Get_Details_From_Tenant_Job
        displayName: 'Get Details From Tenant'
        steps:
          - script: |

             jsonobject='{"adminObject":{"id":"someguid","type":"adminObject","properties":{"flushConfig":false,"storageType":"stream","objectKey":"files.zip","tenantId":"etronds","retryCount":1,"sleepTime":1000}}}'
             deploymentResponse=$(curl -X POST \
              -H 'Content-Type: application/json' \
              -H 'x-rdp-version: 8.1' \
              -H 'x-rdp-tenantId: etronds' \
              -H 'x-rdp-clientId: rdpclient' \
              -H 'x-rdp-userId: etronds.systemadmin@riversand.com' \
              -H 'x-rdp-userRoles: systemadmin' \
              -H 'auth-client-id: j29DTHa7m7VHucWbHg7VvYA75pUjBopS' \
              -H 'auth-client-secret: J7UaRWQgxorI8mdfuu8y0mOLqzlIJo2hM3O4VfhX1PIeoa7CYVX_l0-BnHRtuSWB' \
              -d "$jsonobject" \
              'https://etronds.riversand.com/api/adminservice/deploytenantseed')

              echo "$deploymentResponse"
            displayName: 'Deployment'
