trigger:
  branches:
    include:
      - main  # Replace with your target branch name
      
steps:
- checkout: self

stages:
  - stage: deployDS
    displayName: Deploy DS
    condition: |
      startsWith(variables['Build.SourceBranch'], 'refs/heads/')
    variables:
      - group: DS
    jobs:
      - template: azure-devops/jobs/deploy.yml