trigger:
  branches:
    include:
      - main  # Replace with your target branch name
      
steps:
- checkout: self

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Pipeline.Workspace)/files'  # Replace with the path to your folder in the repository
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Pipeline.Workspace)/output/files.zip'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: 'zip_files'  # Replace with your desired artifact name
    targetPath: '$(Pipeline.Workspace)/output'
