trigger:
  branches:
    include:
      - main  # Replace with your target branch name
      
steps:
- checkout: self

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'  # Replace with the path to your folder in the repository
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifactName: 'artifactName.zip_files'  # Replace with your desired artifact name
    publishLocation: 'pipeline'
   
