trigger: none

pr: none

stages:
  - stage: deployDS
    displayName: Deploy DS
    condition: |
      startsWith(variables['Build.SourceBranch'], 'refs/heads/')
    
    jobs:
      - template: azure-devops/jobs/deploy.yml