trigger:
  branches:
    include:
      - main  # Replace with your target branch name

steps:
- checkout: self

- task: DownloadPipelineArtifact@2
  inputs:
    artifactName: 'ConnectedGitRepo'
    targetPath: '$(Pipeline.Workspace)/files'
    artifactType: 'FilePath'
    itemPattern: '**'


- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Pipeline.Workspace)/files'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Pipeline.Workspace)/output/files.zip'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: 'zip_files'  # Replace with your artifact name
    targetPath: '$(Pipeline.Workspace)/output'
