trigger:
  branches:
    include:
      - main  # Replace with your target branch name

steps:
- checkout: self

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '10-json/110-uiconfig/1106-entitytype/rock-entity-header_product_thing_uiConfig.json'  # Replace with the path to your folder in the repository
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/files.zip'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifactName: 'files'  # Replace with your desired artifact name
    publishLocation: 'pipeline'

- task: cURLUploader@2
  inputs:
    files: '$(Build.ArtifactStagingDirectory)/files.zip'
    authType: ServiceEndpoint
    serviceEndpoint: 'https://etronds.riversand.com/api/binarystreamobjectservice/prepareUpload'
    remotePath: 'upload/$(Build.BuildId)/'
    options:     '--header "Content-Type: application/zip" --header "x-rdp-version: 8.1" --header "x-rdp-tenantId: etronds" --header "x-rdp-clientId: rdpclient" --header "x-rdp-userId: etronds.admin@riversand.com" --header "x-rdp-userRoles: admin" --header "auth-client-id: j29DTHa7m7VHucWbHg7VvYA75pUjBopS" --header "auth-client-secret: J7UaRWQgxorI8mdfuu8y0mOLqzlIJo2hM3O4VfhX1PIeoa7CYVX_l0-BnHRtuSWB"'
