trigger:
  branches:
    include:
      - main  # Replace with your target branch name

variables:
  ZIP_NODE: 'rock-entity-header_product_thing_uiConfig.json'  # Replace with your desired file name

stages:
  - stage: Publish_Zip_File
    displayName: 'Publish Zip File'
    jobs:
      - job: Publish_Zip_File_Job
        displayName: 'Publish Zip File'
        steps:
          - checkout: self

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '10-json/110-uiconfig/1106-entitytype/$(ZIP_NODE)'  # Replace with the path to your folder in the repository
              includeRootFolder: true
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/my_artifact.zip'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'my_artifact'  # Replace with your desired artifact name
              publishLocation: 'pipeline'

          
            displayName: 'Publish Zip File'


          - script: |
              # Define the JSON request body
              jsonBody='{"binaryStreamObject": {"id": "guid","type": "seedDataStream","properties": {"objectKey": "my_artifact.zip","originalFileName": "my_artifact.zip"}}}'
              # Make the POST request and store the response in a variable
              response=$(curl -X POST \
                -H "Content-Type: application/json" \
                -H "x-rdp-version: 8.1" \
                -H "x-rdp-tenantId: etronds" \
                -H "x-rdp-clientId: rdpclient" \
                -H "x-rdp-userId: etronds.systemadmin@riversand.com" \
                -H "x-rdp-userRoles: systemadmin" \
                -H "auth-client-id: j29DTHa7m7VHucWbHg7VvYA75pUjBopS" \
                -H "auth-client-secret: J7UaRWQgxorI8mdfuu8y0mOLqzlIJo2hM3O4VfhX1PIeoa7CYVX_l0-BnHRtuSWB" \
                -d "$jsonBody" \
                'https://etronds.riversand.com/api/binarystreamobjectservice/prepareUpload')

                # Extract the uploadURL from the response using jq
              uploadURL=$(echo "$response" | jq -r '.response.binaryStreamObjects[0].data.properties.uploadURL')
              
              echo "Upload URL: $uploadURL"
              
            displayName: 'Make POST request and extract uploadURL'
                 
          - script: |
              curl -v -X PUT "$uploadURL" \
                --header "x-ms-meta-x_rdp_userroles: systemadmin" \
                --header "x-ms-meta-x_rdp_tenantid: etronds" \
                --header "x-ms-meta-originalfilename: my_artifact.zip" \
                --header "x-ms-blob-content-disposition: attachment; filename=my_artifact.zip" \
                --header "x-ms-meta-type: disposition" \
                --header "x-ms-meta-x_rdp_clientid: rdpclient" \
                --header "x-ms-meta-x_rdp_userid: etronds.systemadmin@riversand.com" \
                --header "x-ms-meta-binarystreamobjectid: guid" \
                --header "x-ms-blob-type: BlockBlob" \
                --header "Content-Type: application/zip" \
                --data-binary "@$(Build.ArtifactStagingDirectory)/my_artifact.zip"

              echo "Folder deployed successfully."
            displayName: 'Deploy Folder'

          - script: |
             jsonobject='{"adminObject":{"id":"someguid","type":"adminObject","properties":{"flushConfig":false,"storageType":"stream","objectKey":"my_artifact.zip","tenantId":"etronds","retryCount":1,"sleepTime":1000}}}'
             deploymentResponse=$(curl -X POST \
              -H 'Content-Type: application/json' \
              -H 'x-rdp-version: 8.1' \
              -H 'x-rdp-tenantId:etronds' \
              -H 'x-rdp-clientId: rdpclient' \
              -H 'x-rdp-userId: etronds.systemadmin@riversand.com' \
              -H 'x-rdp-userRoles: systemadmin' \
              -H 'auth-client-id: j29DTHa7m7VHucWbHg7VvYA75pUjBopS' \
              -H 'auth-client-secret: J7UaRWQgxorI8mdfuu8y0mOLqzlIJo2hM3O4VfhX1PIeoa7CYVX_l0-BnHRtuSWB' \
              -d "$jsonobject" \
              'https://etronds.riversand.com/api/adminservice/deploytenantseed')
             echo "$deploymentResponse"
             status=$(echo "$deploymentResponse" | jq -r '.deploymentResponse.binaryStreamObjects[0].data.properties.status')
             taskId=$(echo "$deploymentResponse" | jq -r '.deploymentResponse.binaryStreamObjects[0].data.properties.taskId')
              
             echo "Status: $status"
             echo "Task ID: $taskId"
             
            displayName: 'Deployment'
